ShowVariationInstanceNames: main.mm
	clang++ -framework ApplicationServices \
		-framework CoreGraphics \
		-framework CoreText \
		-framework Foundation \
		$< -o $@

clean:
	rm -f ShowVariationInstanceNames *~
