showoutline: showoutline.mm
	clang++ -framework ApplicationServices \
		-framework CoreGraphics \
		-framework CoreText \
		-framework Foundation \
		showoutline.mm -o $@

clean:
	rm -f showoutline *~
